#!/bin/bash

#SBATCH -N 1
#SBATCH -A asccasc
#SBATCH -t 2:00:00
#SBATCH -o exaepi.out
#SBATCH --export=ALL

NPROC=25
NNODE=1
NOMP=4

OUTFILE=out.${LCHOST}.log

EXEC=$(ls $EXAEPI_BUILD/bin/*agent*)
echo "Executable file is ${EXEC}."

INP=$(ls inputs*)
echo "Input file is ${INP}."

export OMP_NUM_THREADS=$NOMP
rm -rf Backtrace* plt* cases* $OUTFILE output.dat *.core
srun -N $NNODE -n $NPROC $EXEC $INP 2>&1 |tee $OUTFILE
echo 'Done'
